"""Reproducible notebook export: packages the current dataset plus whichever
analyses were actually run in this session (feature importance, segments,
trend forecast) into a self-contained Jupyter notebook. Every cell is plain
pandas/sklearn/matplotlib code with no dependency on this app's internals, so
the notebook still runs standalone after download — the data itself is
embedded inline, no separate file to lose track of. Zero AI cost, pure code
generation.
"""

import json

import pandas as pd

MAX_EMBEDDED_ROWS = 5000


def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.strip("\n").splitlines(keepends=True),
    }


def _markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.strip("\n").splitlines(keepends=True)}


def build_notebook(
    df: pd.DataFrame,
    dataset_name: str,
    predict_result: dict | None = None,
    segment_result: dict | None = None,
    trend_result: dict | None = None,
) -> dict:
    """Returns an nbformat-v4 notebook dict, ready to be JSON-serialized to .ipynb."""
    cells = [
        _markdown_cell(
            f"# {dataset_name}\n\n"
            "Reproducible notebook generated by **AI Data Analyst** — self-contained, "
            "no app or API key required to rerun."
        ),
        _code_cell("import io\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt"),
    ]

    n_rows = len(df)
    embedded = df if n_rows <= MAX_EMBEDDED_ROWS else df.sample(MAX_EMBEDDED_ROWS, random_state=42)
    sample_comment = (
        "" if n_rows <= MAX_EMBEDDED_ROWS else f"# Sampled {MAX_EMBEDDED_ROWS:,} of {n_rows:,} rows to keep this notebook a reasonable size.\n"
    )
    csv_data = embedded.to_csv(index=False)
    cells.append(
        _code_cell(f"{sample_comment}_csv_data = {csv_data!r}\ndf = pd.read_csv(io.StringIO(_csv_data))\ndf.head()")
    )
    cells.append(_code_cell("df.describe(include='all')"))

    if predict_result and predict_result.get("applicable"):
        target = predict_result["target"]
        task = predict_result["task"]
        cells.append(_markdown_cell(f"## What predicts `{target}`?\n\nBaseline Random Forest {task} model."))
        cells.append(
            _code_cell(
                "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\n"
                "from sklearn.model_selection import train_test_split\n"
                "from sklearn.preprocessing import LabelEncoder\n"
                "from sklearn.metrics import accuracy_score, r2_score\n\n"
                f"target = {target!r}\n"
                "working = df.dropna(subset=[target])\n"
                "feature_columns = [c for c in working.columns if c != target]\n\n"
                "X = working[feature_columns].copy()\n"
                "for col in X.columns:\n"
                "    if not pd.api.types.is_numeric_dtype(X[col]):\n"
                "        X[col] = LabelEncoder().fit_transform(X[col].astype(str))\n"
                "X = X.fillna(X.median(numeric_only=True)).fillna(0)\n\n"
                f"is_classification = {task == 'classification'}\n"
                "y = LabelEncoder().fit_transform(working[target].astype(str)) if is_classification else working[target].to_numpy()\n\n"
                "X_train, X_test, y_train, y_test = train_test_split(\n"
                "    X, y, test_size=0.25, random_state=42, stratify=y if is_classification else None\n"
                ")\n"
                "model = (\n"
                "    RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)\n"
                "    if is_classification\n"
                "    else RandomForestRegressor(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)\n"
                ")\n"
                "model.fit(X_train, y_train)\n"
                "predictions = model.predict(X_test)\n"
                "score = accuracy_score(y_test, predictions) if is_classification else r2_score(y_test, predictions)\n"
                "print(f'{\"accuracy\" if is_classification else \"r2\"}: {score:.3f}')\n\n"
                "importances = sorted(zip(feature_columns, model.feature_importances_), key=lambda p: -p[1])\n"
                "pd.DataFrame(importances, columns=['feature', 'importance'])"
            )
        )

    if segment_result and segment_result.get("applicable"):
        columns_used = segment_result["columns_used"]
        n_clusters = segment_result["n_clusters"]
        cells.append(_markdown_cell(f"## Segments\n\nKMeans clustering into {n_clusters} groups on: {', '.join(columns_used)}."))
        cells.append(
            _code_cell(
                "from sklearn.cluster import KMeans\n"
                "from sklearn.preprocessing import StandardScaler\n"
                "from sklearn.decomposition import PCA\n\n"
                f"segment_columns = {columns_used!r}\n"
                f"n_clusters = {n_clusters}\n\n"
                "working = df[segment_columns].dropna()\n"
                "scaled = StandardScaler().fit_transform(working)\n"
                "labels = KMeans(n_clusters=n_clusters, random_state=42, n_init=10).fit_predict(scaled)\n"
                "working = working.assign(cluster=labels)\n"
                "working.groupby('cluster').mean()"
            )
        )
        cells.append(
            _code_cell(
                "coords = PCA(n_components=2, random_state=42).fit_transform(scaled)\n"
                "fig, ax = plt.subplots(figsize=(7, 5))\n"
                "scatter = ax.scatter(coords[:, 0], coords[:, 1], c=labels, cmap='tab10', alpha=0.7)\n"
                "ax.set_xlabel('PC1')\n"
                "ax.set_ylabel('PC2')\n"
                "ax.set_title(f'{n_clusters} segments found')\n"
                "plt.show()"
            )
        )

    if trend_result and trend_result.get("applicable"):
        date_col = trend_result.get("date_column")
        metric_col = trend_result.get("metric_column")
        agg = trend_result.get("agg", "sum")
        if date_col and metric_col:
            cells.append(_markdown_cell(f"## Trend: `{metric_col}` over `{date_col}`"))
            cells.append(
                _code_cell(
                    f"date_col, metric_col, agg = {date_col!r}, {metric_col!r}, {agg!r}\n"
                    "series = df.copy()\n"
                    "series[date_col] = pd.to_datetime(series[date_col], errors='coerce', format='mixed')\n"
                    "daily = series.dropna(subset=[date_col]).groupby(series[date_col].dt.date)[metric_col].agg(agg)\n"
                    "fig, ax = plt.subplots(figsize=(8, 4))\n"
                    "daily.plot(ax=ax)\n"
                    "ax.set_title(f'{metric_col} over time')\n"
                    "plt.show()"
                )
            )

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def notebook_to_json(notebook: dict) -> str:
    return json.dumps(notebook, indent=1)
